20minutes/colette

assets/styl/_@blocks/_block.styl, assets/styl/_@blocks/_loading.styl, assets/styl/_base/_form-elements.styl, assets/styl/_base/readme.md, assets/styl/_layout/_grid.styl, assets/styl/_mixins/_contrast.styl, assets/styl/_settings.styl, assets/styl/colette.styl, docs/index.html, docs/item--blocks-block-clearfix.html, docs/item--blocks-block-loading.html, docs/item--blocks.html, docs/item-components-forms.html, docs/item-layout-grid.html, docs/item-mixins-contrast-choose.html, docs/item-settings-grid.html, docs/section--blocks.html, docs/section-components.html, docs/section-layout.html, docs/section-mixins.html, docs/section-settings.html, readme.md
- Use caps for CSS, JS and HTML
- Misc typo
=> Fix typo in documentation

.travis.yml, package.json
When using Colette as a dependency, we get an error on the `postinstall` script that build the dist/ and doc files.
This PR removes the gulp `build` and `docs` tasks, and let travis run them instead.
=> Fix: Update build to fix postinstall error when using colette as a dependency

bower.json, kss-builder/styl/co-styles.styl, package.json
I fixed the problem we had with the logo on Firefox. I was only partly visible because of a 'translate' property in CSS. 
I managed it differently.
=> Fixed logo problem on Firefox

assets/styl/_helpers/_colors.styl
I add a fallback on $color-base if theme color has a realy low constast with white.
Useful for `native` theme color
=> Prevent extrem low color ratio

assets/styl/_base/_form.styl, package.json
I fixed the select svg arrow import.
The arrow wasn't visible because of a bad import
Github issue: #314
=> Select arrow

assets/styl/_components/_modal.styl, assets/styl/_components/modal.twig, package-lock.json, package.json
1. Change scroll technique : scroll modal wrapper instead of modal content
2. Add size modifiers for `.modal-window`
=> Change scroll technique for modals and add size modifiers

package-lock.json, package.json, src/styl/_components/_tabpanel.styl
I fixed tabs ability to be styled by inheritance on `text-transform` property if it's a `<button>`
=> Fix button as tab text-transform

package-lock.json, package.json, src/styl/_components/_block.styl
I fixed the color-bottom of the block-title lined.
The original them-color was applied and not the dark one.
I also updated colette-kss-version to have the correct switch colors on the menu
Screenshots before:
after:
=> Blocktitle lined border color

package-lock.json, package.json, src/styl/_elements/_pager.styl
After the add of new pictos arrows, I've fixed their size (to they are more visible) and I've fixed their alignment in the Colette's Pager element
Github issue: Github issue: # https://zube.io/20minutes/vega/c/11543
=> Fix size and alignment of Pager element in Colette

package-lock.json, package.json, src/styl/_elements/_teaser.styl
I fixed line height teaser headline.
=> Fix line height teaser headline

package-lock.json, package.json, src/styl/_helpers/_block.styl
I have added the properties flex: 0, flex: 1, flex: 2, flex: 3 to the flexbox helper
https://zube.io/20minutes/colette/c/569
=> Add flex: X to flexbox helper

package-lock.json, package.json, src/styl/_components/_dropDown.styl, src/styl/_settings/_color.styl, src/styl/_variables/_color.styl
I added the stylus colors variables on the settings, which we haven't anymore since the darkmode.
This section is basically the same as the css variables in the Design section.
I also move the Design.Colors elements into the file css variables, which is more relevent to me.
I also fixed the drop down box-shadow #504 
Github issue: #575
=> Stylus variables on settings

package-lock.json, package.json, src/styl/_elements/_avatar.styl
=> Avatar border is thinner now

.travis.yml, package-lock.json, package.json
Node 8 begins to be obsolete, KSS doesn't support it anymore.
=> Drop node 8 support

src/styl/_components/_preview.styl
By importing the new styles of Colette,
I found that the style of the height of the image of the preview-inline modifier.
https://zube.io/20minutes/vega/c/13411
=> Fix height for img in preview-inline

package-lock.json, package.json, src/styl/_components/_preview.styl
By importing the new styles of Colette,
I found that the style of the height of the image of the preview-inline modifier.
https://zube.io/20minutes/vega/c/13411
=> Fix height for img in preview-inline with release

.travis.yml
Mostly when PR are opened with a branch created on upstream (like it's done by dependabot for example).
For example, that PR is created using a branch pushed to upstream and it should only trigger one build.
Also:
- remove cache of `node_modules` to avoid side effect
- update travis config file
=> Update Travis to avoid double build

.travis.yml
`skip_cleanup` is deprecated and we should use `cleanup` but the value should be switched : `skip_cleanup: true` must become `cleanup: false`
=> Don't clean up build result

src/styl/_components/_modal.styl
I add the doc comment for modal hidden button style
Github issue: https://zube.io/20minutes/vega/c/13680
=> Add doc comment for modal hidden button

src/js/pager.js
I fixed the pager that in negative on firefox when you went on the second page and you refreshed the page.
Github issue: https://zube.io/20minutes/vega/c/14357
Don’t forget to: mark if your Pull Request is Ready For Review, Work In Progress.
=> Firefox pager go in negative fix

package-lock.json, package.json
`@babel/eslint-parser` must be a dev deps.
Following https://github.com/20minutes/colette/pull/886
=> Move @babel/eslint-parser to dev deps

.github/workflows/github-pages.yml, .github/workflows/publish.yml, package-lock.json
It was already done for test, but needed to be applied to GitHub Pages & NPM publish workflow.
The main idea is to bypass the error generated when installing deps:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ryuran/postcss-custom-properties.git
npm ERR!
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```
- https://github.com/20minutes/colette/runs/2501720190?check_suite_focus=true
- …
=> Reconfigure git to use HTTP authentication in workflow

webpack.config.js
There were some regressions since the upgrade to Webpack V5: resources like img used for demo, fonts, favicon were on 404. 
They weren't simply not imported.
I also removed the call to `file-loader` since it became obsolete
Before:
After:
=> Fix webpack resources import

webpack.config.js
This relates to the previous #1181
While the issue of resources not imported is fixed on dev environment, it still persist on production.
So I moved the CopyPlugin from the env. dev.
This should solve it
=> Fix resources import on production

package-lock.json, package.json, src/styl/_components/_accordion.styl, src/styl/_components/accordion.twig
The font size of the title  was applied on the button and not the title.
This can be problemtic if we want to add some subtitles in the panels
=> Fix accordion font-size

package-lock.json, package.json, src/styl/_components/_breakingnews.styl, src/styl/_components/breakingnews.twig, src/svg/flash.svg
I changed styl of the breaking news component for the new integration in vega project.We want to show it at the bottom of the page and on top of the toolbar when both are present.
i remove all styl for dark mode cause he never change.
Github issue: #11092 https://zube.io/20minutes/vega/c/17805
before : 
After :
=> New styl for breaking news component

package-lock.json, package.json, src/styl/_components/_preview.styl
I fixed the styl of preview class, for catchline default styl the goal is to be able to meet the need for the catchline and therefore be able to change the basic state which was with a yellow background
Github issue: #11190 https://zube.io/20minutes/vega/c/18103
=> Change Preview class for catchline 

package-lock.json, package.json, src/styl/_components/_breakingnews.styl, src/styl/_components/breakingnews.twig
I reverted styl of breakingnews banner cause is not ready to be deployed in master.
for me is the better solution to make a something clean in the workflow
Github issue: #11126
=> Revert breaking news elements styl

package-lock.json, package.json, src/styl/_components/_breakingnews.styl, src/styl/_components/breakingnews.twig
I changed styl of the breaking news component for the new integration in vega project.We want to show it at the bottom of the page and on top of the toolbar when both are present.
i remove all styl for dark mode cause he never change.
Github issue: #1216 
before : 
After :
=> New styl for breaking-news banner
