.gitignore, bower.json, styl/_modules/_navbar.styl
=> Add styles for navbar

assets/styl/_layout/_grid.styl, assets/styl/_layout/_spaces.styl, assets/styl/_modules/_tabs.styl, assets/styl/_settings.styl, bower.json, package.json
- make settings overridable
- make grid customizable by adding/overriding breakpoints
- create mixins to easily define gutter-based spacers or grid-based width
=> Make setting customizable and upgrade grid and spacers

assets/styl/_layout/_buttons.styl, bower.json, package.json
=> Add styles for text buttons

assets/styl/_helpers/_colors.styl, assets/styl/_modules/_tabs.styl, assets/styl/_settings.styl
Impacts:
https://github.com/20minutes/hekla/blob/master-fusion/app/Resources/assets/styl/_modules/_block.styl#L99-L113
https://github.com/20minutes/hekla/blob/master-fusion/app/Resources/assets/styl/_layout/_content.styl#L61-L63
https://github.com/20minutes/hekla/blob/master-fusion/app/Resources/assets/styl/_modules/_pager.styl#L48-L51
=> move categories color to hashes

assets/styl/_base/_form-elements.styl, bower.json, package.json
=> fix #83 textarea baseline

bower.json, package.json
=> up version and add headroom for npm install

bower.json, package.json
I just fixed colette's version for media tag scalability
=> Fixed colette's version for media tag scalability

.travis.yml
Avoid 3 deployment when merging on master
=> Don't deploy on each build

.travis.yml, package.json
Remove the private property to be able to publish it on NPM
=> Ready for NPM

bower.json, package.json
Just fixing the version number in order to draft a new release (related to @j0k3r latest release)
=> Fixed colette version

package.json
Call to the fontface.json file was missing in package.json
=> Add font face call in package.json

gulpfile.js, package-lock.json, package.json
Everything is in the title and the commit's message :
Upgrade Gulp version to v4.
Github issue: #207
=> Mise à jour de gulp -> v4

kss.json, package-lock.json, package.json
https://github.com/kss-node/kss-node/issues/467
=> Fix twig js version

assets/styl/_components/socialbar.json, assets/styl/_settings/_color.styl, assets/styl/_themes/_btnSkin.styl, assets/svg/social/flipboard.svg, package-lock.json, package.json
New social "flipboard" icon added
=> Add new social icon: flipboard

assets/styl/_components/_block.styl, assets/styl/_components/_tabpanel.styl, assets/styl/_helpers/_align.styl, assets/styl/_helpers/_fs.styl, package-lock.json, package.json
=> Remove border top on block footer + add font-size helpers + improve tabpanels

assets/styl/_components/_card.styl, assets/styl/_components/block-list-with-cards.json, package-lock.json, package.json
=> Fix line number for cards

assets/styl/_layouts/_list.styl, assets/styl/_layouts/grid.twig, assets/styl/_layouts/list.twig, assets/styl/_settings/_grid.styl, assets/styl/_settings/_list.styl, package-lock.json, package.json, readme.md
I'm trying to create properly the 'list' layout in colette.
=> Creating 'list' layout

assets/js/colette.js, assets/styl/_components/_tabpanel.styl, gulpfile.js, package-lock.json, package.json
I fixed Tablist implementation because v2 API was different.
=> Fix tablist

assets/styl/_components/_block.styl, package.json
=> fix IE11 flex blocklist

assets/styl/_elements/_btn.styl, assets/styl/_elements/_formSingleInput.styl, assets/styl/_elements/avatar.twig, assets/styl/_elements/media.json, assets/styl/_themes/_btnSkin.styl, assets/styl/_themes/btnSkin.twig, package-lock.json, package.json
Add new btn modifier `line`
I fix hover on link btn
=> Add new btn modifier `line`

assets/js/colette.js, assets/styl/_components/_box.styl, assets/styl/_components/box.twig, gulpfile.js, package-lock.json, package.json
=> Add box-lined modifier

assets/styl/_helpers/_colors.styl, package-lock.json, package.json
Border color helpers should only modify `border-color` property
=> Fix border color helpers

.travis.yml, package.json
=> Fix release to NPM

assets/js/colette.js, assets/js/modules/modal.js, assets/styl/_components/_modal.styl, assets/styl/_components/modal.twig, package-lock.json, package.json
I add a modifier class to modal-window to position the close button outside the modal panel
Breaking change because rename some classes
=> Add modal-window with close button outside

package-lock.json, package.json
=> Fix npm package

package-lock.json, package.json, src/styl/_elements/_icon.styl, src/styl/_elements/_loading.styl, src/styl/_mixins/_spaces.styl
Fix #318 : I add possibility to use value with unit and keyword in spaces mixins
Github issue: #318
=> Allow value with unit and keyword in spaces mixins

package-lock.json, package.json, src/styl/_components/_content.styl, src/styl/_elements/_media.styl
I fixed line-height related styl in content
=> Fix content style related to line-height

package-lock.json, package.json, src/styl/_variables/_color.styl
--color-bg-base & --color-bg-primary were inverted.
Github issue: https://zube.io/20minutes/vega/c/10855
=> Fix background color on dark mode

package-lock.json, package.json, src/styl/_base/_init.styl, src/styl/_elements/_pager.styl, src/styl/_settings/_color.styl, src/styl/_variables/_color.styl
I removed the height 100% for the body 
I fixed the color of the disabled pager
I changed the color of the links for the dark mode
Github issue: https://zube.io/20minutes/vega/c/10879
=> Dark mode enhancement

package-lock.json, package.json, src/styl/_components/_block.styl
The color of the title lined didn't change on dark theme
before: 
after:
=> Block Title Lined dark color

package-lock.json, package.json, src/styl/_helpers/_colors.styl
I add helpers for native foreground color
=> Add helpers for native foreground color

package-lock.json, package.json, src/styl/_themes/_skin.styl
I changed last minute text from "Dernière minute" to "alerte info" 
https://zube.io/20minutes/vega/c/10475
=> Update skin last minute text

package-lock.json, package.json, src/styl/_helpers/_fillColors.styl, src/styl/_helpers/colors.twig
I have created the fill-color helper,
and added the examples of color/bg-color-border-color/fill-color
https://zube.io/20minutes/colette/c/524
=> Add fill-color helper

package-lock.json, package.json, src/styl/_helpers/_block.styl
I added the flexbox helpers, for display, direction, flow, wrap, align, justify-content
Github issue: https://zube.io/20minutes/vega/c/11309
=> Add of the flexbox helper

package-lock.json, package.json, src/styl/_components/_modal.styl, src/styl/_components/modal.twig
This is useful for very long content inside a modal, CGU for exemple
=> Add a modifier fixed height for the modal

src/styl/_mixins/_lh.styl
I fixed lines mixins documentation.
=> Fix doc for line height

kss.json, package.json
The homepage is down since the upgrade of kss  #571
=> Fix kss parameters

README.md
Include the webpack config in case of using it instead of gulp.
Most of 20 Minutes projects are using webpack
Github issue: #434
=> Improve readme with webpack config

package.json
I added the true real homepage.
=> Change homepage

package-lock.json, package.json, src/styl/_components/_preview.styl
I fixed the style for the modifier preview-forward
(because the basic style was modified by the style of .preview .class-of-skin)
https://zube.io/20minutes/vega/c/13411
- Before
- After
=> Fix preview-forward style

.travis.yml
Looks like it fails no mater what change we apply, revert back to the config v1 from Travis
=> Revert changes on deployment

package-lock.json, package.json
=> Release 5.2.5

package-lock.json, package.json, src/styl/_components/_modal.styl
I added the style for the class .modal-window-closeHidden, which allows to hide the close button in a modal.
https://zube.io/20minutes/vega/c/13680
=> Add modal button hidden style

package-lock.json, package.json, src/styl/_components/_footerbar.styl, src/styl/_components/footerbar.twig, src/styl/_helpers/_fs.styl
i changed the style and the markup for the footer
Before : 
After :
Github issue: #9075
=> update new footer style and markup

package-lock.json, package.json, src/styl/_components/_inlinemenu.styl, src/styl/_components/inlinemenu.twig
i create a new view and styl for inline-menu 
=> Create a new component for inline menu

package-lock.json, package.json
=> Feature : new version 

package-lock.json, package.json, src/styl/_base/_typography.styl
I try to fix hyphens issue on some browsers. It seems to add useless line breaks inside paragraphs using links.
Note: it's just a test as we don't know exactly why this behavior is not consistant through browsers.
Linked PR: https://github.com/20minutes/colette/pull/825
=> Fix issue with hyphens - test

package-lock.json, package.json
=> Add version 5.3.5 to npm

package-lock.json, package.json, src/styl/_themes/_skin.styl
I changed skin summer content name
Github issue: #9762 https://zube.io/20minutes/vega/c/14759
Don’t forget to: mark if your Pull Request is Ready For Review, Work In Progress.
=> Change skin summer content name

package-lock.json, package.json, src/svg/bookmars2.svg
I fixed…
Github issue: #9942 https://zube.io/20minutes/vega/c/15398
=> add active bookmarks icon

src/styl/_settings/_color.styl
I fixed color of color-background-2
=> change notice color-background-2

webpack.config.js
Following https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md since we upgraded from v3 to v4
=> webpack-dev-server migration

package-lock.json, package.json, src/styl/_helpers/_cursor.styl, src/styl/_helpers/helpers-cursor.twig
I added a new section in helpers for cursor type
Github issue: #10980 https://zube.io/20minutes/vega/c/17244
=> Add new helper to change cursor

package-lock.json, package.json, src/index.js, src/styl/_components/_accordion.styl, src/styl/_components/accordion.twig, src/styl/_settings/_color.styl
A simple & accessible Accordion, using https://www.npmjs.com/package/@accede-web/accordion
To keep this accordion accessible AND match with the desired design, we have to be a bit tricky:
The button changes and "fusion" with it's content when open
I also fixed some colors which were not correct on the demo.
=> New component: Accordion

package-lock.json, package.json
=> Prepare 5.6.9
